id: P004222
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:02:29.701906
source_metadata:
  id: bdr:W1KG11817
  title: བཀྲ་ཤིས་ལྷུན་པོའི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    34971db84d204db5aecaae87e3cfbb33:
      image_group_id: I1KG11819
      title: ''
      volume_number: 1
      total_pages: 570
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
